SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE COMMENT;
TRUNCATE TABLE POST;
TRUNCATE TABLE VISITOR_SEQ;
TRUNCATE TABLE VISITOR;
TRUNCATE TABLE VOTE;
TRUNCATE TABLE FILE;
TRUNCATE TABLE BOARD;
TRUNCATE TABLE MEMBER;

SET FOREIGN_KEY_CHECKS = 1;